- name: Install utility packages
  apt:
    package: sudo,chromium,vim,htop

- name: Make sure user stepmania is in sudo group
  user:
    name: stepmania
    groups: sudo
    append: yes

- name: Disable apt-daily-service.timer
  systemd:
    name: apt-daily-upgrade.timer
    enabled: no
    state: stopped

- name: Disable apt-daily.timer
  systemd:
    name: apt-daily.timer
    enabled: no
    state: stopped

- name: Remove light-locker from autostart
  file:
    path: /etc/xdg/autostart/light-locker.desktop
    state: absent

- name: Remove xscreensaver from autostart
  file:
    path: /etc/xdg/autostart/xscreensaver.desktop
    state: absent
